### ISSUE TITLE
HARD TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by adideas** [nativescript-vue/nativescript-vue.org#344]
**Hi**

This work on NS 6.5 and dont work NS (NativeScript) 7.0
(Это работает на NS6.5 и не работает на NS 7.0)

TEMPLATE:

```
<absolute-layout>
         <login-show />
</absolute-layout>
```

OR TEMPLATE

```
<absolute-layout>
         <component is="LoginShow"/>
</absolute-layout>
```

OR TEMPLATE

```
<absolute-layout>
         <LoginShow />
</absolute-layout>
```

ERROR:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{******/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{******/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3051)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3198)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1893)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:192)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7169)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
System.err:     at android.app.Activity.performCreate(Activity.java:8623)
System.err:     at android.app.Activity.performCreate(Activity.java:8614)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1274)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3028)
System.err:     ... 11 more
```

**This work on NS 6.5 and dont work NS 7.0!**

Any use of the component results in an error!
(Любое использование компонента приводит к ошибке)

Is this really the end of it?

**Comment by adideas** [comment]
I rollback ns 6 ((((

**Comment by gbelot2003** [comment]
> I rollback ns 6 ((((

wow, I have the same problem on NS 7 a year letter

**Comment by rigor789** [comment]
@gbelot2003 can't fix something that I cannot reproduce - please open a new issue with more details in the https://github.com/nativescript-vue/nativescript-vue repo...
