### ISSUE TITLE
Cannot read property 'getKeyedTemplates' of undefined

### ISSUE THREAD

**Issue by sant123** [nativescript-vue/nativescript-vue.org#48]
Hi and thank you for this awesome plugin. I have been looking for the examples in the `nativescript-vue-template` but it seems one is failing.

Running the template `app-with-list-view.js` crashes the app.

Here is the full exception:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.myapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'getKeyedTemplates' of undefined
File: "file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js, line: 2137, column: 6

StackTrace: 
	Frame: function:'mounted', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 10798, column: 22
	Frame: function:'callHook', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3217, column: 21
	Frame: function:'insert', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9681, column: 7
	Frame: function:'invokeInsertHook', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3777, column: 28
	Frame: function:'patch', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3996, column: 5
	Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2959, column: 19
	Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3087, column: 10
	Frame: function:'get', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2132, column: 25
	Frame: function:'Watcher', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2121, column: 12
	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3094, column: 3
	Frame: function:'create', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 11173, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'getKeyedTemplates' of undefined
File: "file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js, line: 2137, column: 6

StackTrace: 
	Frame: function:'mounted', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 10798, column: 22
	Frame: function:'callHook', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3217, column: 21
	Frame: function:'insert', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9681, column: 7
	Frame: function:'invokeInsertHook', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3777, column: 28
	Frame: function:'patch', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3996, column: 5
	Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2959, column: 19
	Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3087, column: 10
	Frame: function:'get', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2132, column: 25
	Frame: function:'Watcher', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2121, column: 12
	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3094, column: 3
	Frame: function:'create', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-vue/dist/index.js', line: 11173, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.myapp/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	... 9 more
```

**Comment by rigor789** [comment]
Ah it has not been updated in the template, here is the working source: https://github.com/nativescript-vue/nativescript-vue/blob/master/samples/app/app-with-list-view.js

**Comment by sant123** [comment]
Thank you @rigor789. Now works 😋
